apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: cloudregistrydemo.azurecr.io/azvote/azure-vote-front
    newTag: 3c0904972121dec4d7a2e660ac9c6139d0fa9bd5
  - name: cloudregistrydemo.azurecr.io/azvote/azure-vote-back
    newTag: 3c0904972121dec4d7a2e660ac9c6139d0fa9bd5
resources:
  - manifests.yaml