apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: cloudregistrydemo.azurecr.io/azvote/azure-vote-front
    newTag: a11567981ed4298614b296d69b73e2cd6997e39b
  - name: cloudregistrydemo.azurecr.io/azvote/azure-vote-back
    newTag: a11567981ed4298614b296d69b73e2cd6997e39b
resources:
  - manifests.yaml