apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: haojiehanglaxregistry.azurecr.io/azvote/azure-vote-front
    newTag: 7feb62ca9451c209314bc45953167b60ff37b18e
  - name: haojiehanglaxregistry.azurecr.io/azvote/azure-vote-back
    newTag: 7feb62ca9451c209314bc45953167b60ff37b18e
resources:
  - manifests.yaml